# Generated by Django 4.2.14 on 2024-10-02 07:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='voice_type',
            field=models.CharField(default=datetime.datetime(2024, 10, 2, 7, 26, 53, 919675, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
    ]
