# Generated by Django 4.2.14 on 2024-10-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_story_created_at_story_voice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='story',
            name='voice_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='interests',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('page_number', models.IntegerField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.story')),
            ],
        ),
    ]
